// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/stats.proto

package stats

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StatsService_IncrementAccessCount_FullMethodName = "/stats.StatsService/IncrementAccessCount"
	StatsService_GetAccessCount_FullMethodName       = "/stats.StatsService/GetAccessCount"
)

// StatsServiceClient is the client API for StatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsServiceClient interface {
	IncrementAccessCount(ctx context.Context, in *IncrementAccessCountRequest, opts ...grpc.CallOption) (*IncrementAccessCountResponse, error)
	GetAccessCount(ctx context.Context, in *GetAccessCountRequest, opts ...grpc.CallOption) (*GetAccessCountResponse, error)
}

type statsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsServiceClient(cc grpc.ClientConnInterface) StatsServiceClient {
	return &statsServiceClient{cc}
}

func (c *statsServiceClient) IncrementAccessCount(ctx context.Context, in *IncrementAccessCountRequest, opts ...grpc.CallOption) (*IncrementAccessCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementAccessCountResponse)
	err := c.cc.Invoke(ctx, StatsService_IncrementAccessCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statsServiceClient) GetAccessCount(ctx context.Context, in *GetAccessCountRequest, opts ...grpc.CallOption) (*GetAccessCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccessCountResponse)
	err := c.cc.Invoke(ctx, StatsService_GetAccessCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsServiceServer is the server API for StatsService service.
// All implementations must embed UnimplementedStatsServiceServer
// for forward compatibility.
type StatsServiceServer interface {
	IncrementAccessCount(context.Context, *IncrementAccessCountRequest) (*IncrementAccessCountResponse, error)
	GetAccessCount(context.Context, *GetAccessCountRequest) (*GetAccessCountResponse, error)
	mustEmbedUnimplementedStatsServiceServer()
}

// UnimplementedStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStatsServiceServer struct{}

func (UnimplementedStatsServiceServer) IncrementAccessCount(context.Context, *IncrementAccessCountRequest) (*IncrementAccessCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementAccessCount not implemented")
}
func (UnimplementedStatsServiceServer) GetAccessCount(context.Context, *GetAccessCountRequest) (*GetAccessCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessCount not implemented")
}
func (UnimplementedStatsServiceServer) mustEmbedUnimplementedStatsServiceServer() {}
func (UnimplementedStatsServiceServer) testEmbeddedByValue()                      {}

// UnsafeStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatsServiceServer will
// result in compilation errors.
type UnsafeStatsServiceServer interface {
	mustEmbedUnimplementedStatsServiceServer()
}

func RegisterStatsServiceServer(s grpc.ServiceRegistrar, srv StatsServiceServer) {
	// If the following call pancis, it indicates UnimplementedStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StatsService_ServiceDesc, srv)
}

func _StatsService_IncrementAccessCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementAccessCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).IncrementAccessCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_IncrementAccessCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).IncrementAccessCount(ctx, req.(*IncrementAccessCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatsService_GetAccessCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatsServiceServer).GetAccessCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StatsService_GetAccessCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatsServiceServer).GetAccessCount(ctx, req.(*GetAccessCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatsService_ServiceDesc is the grpc.ServiceDesc for StatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stats.StatsService",
	HandlerType: (*StatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IncrementAccessCount",
			Handler:    _StatsService_IncrementAccessCount_Handler,
		},
		{
			MethodName: "GetAccessCount",
			Handler:    _StatsService_GetAccessCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stats.proto",
}
